# Generated by Django 3.2 on 2021-04-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90, verbose_name='Nome do jogo:')),
                ('qtd_jogadores', models.IntegerField(verbose_name='Quantidades de jogadores:')),
                ('nivel_jogo', models.CharField(choices=[('f', 'Fácil'), ('m', 'Médio'), ('d', 'Dificil'), ('xtd', 'X-tudo')], max_length=90, verbose_name='Nível do jogo:')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'db_table': 'new_game_jogo',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=20, verbose_name='Nome completo do jogador:')),
                ('pontuacao', models.IntegerField(verbose_name='Pontuação:')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_game.jogo')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'db_table': 'new_game_jogador',
            },
        ),
    ]
