# Generated by Django 3.2 on 2021-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='pontuacao',
            field=models.IntegerField(default=0, verbose_name='Pontuação:'),
        ),
    ]
