# Generated by Django 3.2 on 2021-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_game', '0004_alter_desafios_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafios',
            name='nivel_frase',
            field=models.CharField(choices=[('f', 'Fácil'), ('m', 'Médio'), ('d', 'Dificil')], max_length=90, verbose_name='Nível da frase:'),
        ),
    ]
