# Generated by Django 3.2 on 2021-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_game', '0005_alter_desafios_nivel_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regracasa',
            name='frase',
            field=models.CharField(max_length=200, verbose_name='Regras da casa:'),
        ),
    ]
