# Generated by Django 3.2 on 2021-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_game', '0006_alter_regracasa_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='nome',
            field=models.CharField(max_length=11, verbose_name='Nome do jogo:'),
        ),
    ]
