# Generated by Django 3.2 on 2021-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_game', '0007_alter_jogo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do jogo:'),
        ),
    ]
