# Generated by Django 3.2 on 2021-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_game', '0008_alter_jogo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='qtd_jogadores',
            field=models.PositiveIntegerField(verbose_name='Quantidades de jogadores:'),
        ),
    ]
